"""Add paid column to contributions

Revision ID: 72253566a2cd
Revises: 
Create Date: 2026-01-11 12:26:59.375773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72253566a2cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contributions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contributions', schema=None) as batch_op:
        batch_op.drop_column('paid')

    # ### end Alembic commands ###
